name: "Build & Test"

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
  workflow_dispatch:
    inputs:
      override-cdt:
        description: 'Override cdt target'
        type: string
      override-cdt-prerelease:
        type: choice
        description: Override cdt prelease
        options:
        - default
        - true
        - false
      override-reference-contracts:
        description: 'Override reference contracts ref'
        type: string

permissions:
  packages: read
  contents: read

defaults:
  run:
    shell: bash

jobs:
  platform-cache:
    name: Platform Cache
    uses: AntelopeIO/platform-cache-workflow/.github/workflows/platformcache.yaml@v1
    permissions:
      packages: write
      contents: read
    with:
      runs-on: '["self-hosted", "enf-x86-beefy"]'
      platform-files: |
        .cicd/platforms
        tools/reproducible.Dockerfile:builder

  build-base:
    name: Run Build Workflow
    uses: ./.github/workflows/build_base.yaml
    needs: [platform-cache]
    with:
      platforms: ${{needs.platform-cache.outputs.platforms}}
      platform-list: ${{needs.platform-cache.outputs.platform-list}}

  v:
    name: Discover Versions
    runs-on: ubuntu-latest
    outputs:
      cdt-target: ${{steps.versions.outputs.cdt-target}}
      cdt-prerelease: ${{steps.versions.outputs.cdt-prerelease}}
      reference-contracts-ref: ${{steps.versions.outputs.reference-contracts-ref}}
    steps:
      - name: Setup cdt and reference-contracts versions
        id: versions
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          DEFAULTS_JSON=$(curl -sSfL $(gh api https://api.github.com/repos/${{github.repository}}/contents/.cicd/defaults.json?ref=${{github.sha}} --jq .download_url))
          echo cdt-target=$(echo "$DEFAULTS_JSON" | jq -r '.cdt.target') >> $GITHUB_OUTPUT
          echo cdt-prerelease=$(echo "$DEFAULTS_JSON" | jq -r '.cdt.prerelease') >> $GITHUB_OUTPUT
          echo reference-contracts-ref=$(echo "$DEFAULTS_JSON" | jq -r '.referencecontracts.ref') >> $GITHUB_OUTPUT

          if [[ "${{inputs.override-cdt}}" != "" ]]; then
            echo cdt-target=${{inputs.override-cdt}} >> $GITHUB_OUTPUT
          fi
          if [[ "${{inputs.override-cdt-prerelease}}" == +(true|false) ]]; then
            echo cdt-prerelease=${{inputs.override-cdt-prerelease}} >> $GITHUB_OUTPUT
          fi
          if [[ "${{inputs.override-reference-contracts}}" != "" ]]; then
            echo reference-contracts-ref=${{inputs.override-reference-contracts}} >> $GITHUB_OUTPUT
          fi

  tests:
    name: Tests (${{matrix.cfg.name}})
    needs: [platform-cache, build-base]
    strategy:
      fail-fast: false
      matrix:
        include:
          - cfg: {name: 'ubuntu22repro', base: 'ubuntu22', builddir: 'reproducible'}
    runs-on: ["self-hosted", "enf-x86-hightier"]
    container:
      image: ${{fromJSON(needs.platform-cache.outputs.platforms)[matrix.cfg.base].image}}
      options: --security-opt seccomp=unconfined --mount type=bind,source=/var/lib/systemd/coredump,target=/cores
    steps:
      - uses: actions/checkout@v4
      - name: Download builddir
        uses: actions/download-artifact@v4
        with:
          name: ${{matrix.cfg.builddir}}-build
      - name: Wait for core files to populate
        uses: ./.github/actions/wait-for-cores
      - name: Upload core files from failed tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{matrix.cfg.name}}-tests-logs
          if-no-files-found: ignore
          path: /cores
          compression-level: 0
      - name: Check CPU Features
        run: awk 'BEGIN {err = 1} /bmi2/ && /adx/ {err = 0} END {exit err}' /proc/cpuinfo

  np-tests:
    name: NP Tests (${{matrix.cfg.name}})
    needs: [platform-cache, build-base]
    strategy:
      fail-fast: false
      matrix:
        include:
          - cfg: {name: 'ubuntu22',      base: 'ubuntu22', builddir: 'ubuntu22'}
    runs-on: ["self-hosted", "enf-x86-midtier"]
    steps:
      - uses: actions/checkout@v4
      - name: Download builddir
        uses: actions/download-artifact@v4
        with:
          name: ${{matrix.cfg.builddir}}-build
      - name: Wait for core files to populate
        uses: ./.github/actions/wait-for-cores
        if: failure()
      - name: Export core dumps
        run: docker run --mount type=bind,source=/var/lib/systemd/coredump,target=/cores alpine sh -c 'tar -C /cores/ -c .' | tar x
        if: failure()
      - name: Upload logs from failed tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{matrix.cfg.name}}-np-logs
          path: |
            *-logs.tar.gz
            core*.zst
          compression-level: 0
