name: Release Actions

on:
  release:
    types: [published]

jobs:
  eb:
    name: experimental-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - name: Get ubuntu20 antelope-spring-dev.deb
        uses: AntelopeIO/asset-artifact-download-action@v3
        with:
          owner: ${{github.repository_owner}}
          repo: ${{github.event.repository.name}}
          file: 'antelope-spring-dev.*amd64.deb'
          target: ${{github.sha}}
          artifact-name: antelope-spring-dev-ubuntu20-amd64
          wait-for-exact-target: true
      - name: Get ubuntu22 antelope-spring-dev.deb
        uses: AntelopeIO/asset-artifact-download-action@v3
        with:
          owner: ${{github.repository_owner}}
          repo: ${{github.event.repository.name}}
          file: 'antelope-spring-dev.*amd64.deb'
          target: ${{github.sha}}
          artifact-name: antelope-spring-dev-ubuntu22-amd64
          wait-for-exact-target: true
      - name: Create Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM scratch
          LABEL org.opencontainers.image.description="A collection of experimental Spring binary packages"
          COPY *.deb /
          EOF
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{github.token}}
      - run: echo "REPOSITORY_OWNER_LOWER=${GITHUB_REPOSITORY_OWNER,,}" >> "${GITHUB_ENV}"
      - name: Build and push antelope-spring-experimental-binaries
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{env.REPOSITORY_OWNER_LOWER}}/antelope-spring-experimental-binaries:${{github.ref_name}}
          context: .
